const bi = (en, hi) => Object.freeze({ en, hi });
const item = (titleEn, titleHi, bodyEn, bodyHi, route = "") => Object.freeze({
  title: bi(titleEn, titleHi), body: bi(bodyEn, bodyHi), route
});
const field = (name, type, labelEn, labelHi, options = {}) => Object.freeze({
  name, type, label: bi(labelEn, labelHi), ...options
});
const page = (id, group, composition, labelEn, labelHi, titleEn, titleHi, introEn, introHi, options = {}) => Object.freeze({
  id, group, composition, label: bi(labelEn, labelHi),
  eyebrow: bi(options.eyebrowEn || labelEn, options.eyebrowHi || labelHi),
  title: bi(titleEn, titleHi), intro: bi(introEn, introHi),
  items: Object.freeze(options.items || []), fields: Object.freeze(options.fields || []),
  sources: Object.freeze(options.sources || []), result: options.result ? bi(options.result.en, options.result.hi) : null
});

const incidentFields = [
  field("incidentDate", "date", "When did it happen?", "यह कब हुआ?", { required: true }),
  field("category", "select", "What best describes it?", "इसका सबसे सही विवरण क्या है?", {
    required: true,
    options: [bi("Financial fraud", "वित्तीय धोखाधड़ी"), bi("Threat or harassment", "धमकी या उत्पीड़न"), bi("Identity misuse", "पहचान का दुरुपयोग"), bi("Other cybercrime", "अन्य साइबर अपराध")]
  }),
  field("description", "textarea", "What happened?", "क्या हुआ?", { required: true, minLength: 24 })
];

export const PORTAL_ROUTES = Object.freeze([
  page("complaints", "complaints", "hub", "Complaint services", "शिकायत सेवाएँ", "Choose the right complaint path", "सही शिकायत मार्ग चुनें", "Start locally with clear preparation. Nothing here reaches a government system.", "स्पष्ट तैयारी के साथ स्थानीय रूप से शुरू करें। यहाँ से कोई जानकारी सरकारी प्रणाली तक नहीं जाती।", {
    sources: ["officialComplaint"], items: [
      item("Women and children", "महिलाएँ और बच्चे", "Understand anonymous and registered options.", "गुमनाम और पंजीकृत विकल्प समझें।", "women-children"),
      item("Financial fraud", "वित्तीय धोखाधड़ी", "Prepare evidence through the complete guided flow.", "पूर्ण निर्देशित प्रवाह में साक्ष्य तैयार करें।", "act-now"),
      item("Other cybercrime", "अन्य साइबर अपराध", "Create a synthetic complaint draft.", "एक सिंथेटिक शिकायत मसौदा बनाएँ।", "other-cybercrime")
    ]
  }),
  page("women-children", "complaints", "guidance", "Women and children", "महिलाएँ और बच्चे", "Reporting options for women and children", "महिलाओं और बच्चों के लिए रिपोर्टिंग विकल्प", "Choose an anonymous practice route or a registered practice route. Both remain local simulations.", "गुमनाम या पंजीकृत अभ्यास मार्ग चुनें। दोनों स्थानीय सिमुलेशन हैं।", {
    sources: ["officialComplaint"], items: [
      item("Report anonymously", "गुमनाम रिपोर्ट", "Practice describing an incident without identity fields.", "पहचान फ़ील्ड के बिना घटना बताने का अभ्यास करें।", "anonymous-report"),
      item("Registered complaint", "पंजीकृत शिकायत", "Practice a fuller complaint with synthetic contact details.", "सिंथेटिक संपर्क विवरण के साथ पूरी शिकायत का अभ्यास करें।", "registered-report"),
      item("Immediate safety", "तत्काल सुरक्षा", "If anyone is in immediate danger, contact local emergency services directly.", "तत्काल खतरे में स्थानीय आपात सेवा से सीधे संपर्क करें।")
    ]
  }),
  page("anonymous-report", "complaints", "form", "Anonymous practice", "गुमनाम अभ्यास", "Prepare an anonymous complaint draft", "गुमनाम शिकायत मसौदा तैयार करें", "Use fictional details only. This draft is erased when the page reloads.", "केवल काल्पनिक विवरण दें। पेज रीलोड होने पर मसौदा मिट जाएगा।", { fields: incidentFields, sources: ["officialComplaint"], result: bi("Anonymous draft prepared locally", "गुमनाम मसौदा स्थानीय रूप से तैयार") }),
  page("registered-report", "complaints", "form", "Registered practice", "पंजीकृत अभ्यास", "Prepare a registered complaint draft", "पंजीकृत शिकायत मसौदा तैयार करें", "Use the synthetic examples shown; do not enter real personal information.", "दिए गए सिंथेटिक उदाहरणों का उपयोग करें; वास्तविक व्यक्तिगत जानकारी न भरें।", {
    fields: [field("fullName", "text", "Synthetic full name", "सिंथेटिक पूरा नाम", { required: true, minLength: 3, example: "Demo Citizen" }), field("email", "email", "Synthetic email", "सिंथेटिक ईमेल", { required: true, example: "citizen@example.test" }), ...incidentFields], sources: ["officialComplaint"], result: bi("Registered draft prepared locally", "पंजीकृत मसौदा स्थानीय रूप से तैयार")
  }),
  page("other-cybercrime", "complaints", "form", "Other cybercrime", "अन्य साइबर अपराध", "Prepare another cybercrime complaint", "अन्य साइबर अपराध शिकायत तैयार करें", "Organise the basic facts before using an official channel.", "आधिकारिक माध्यम उपयोग करने से पहले मूल तथ्य व्यवस्थित करें।", { fields: incidentFields, sources: ["officialComplaint"], result: bi("Cybercrime draft prepared locally", "साइबर अपराध मसौदा स्थानीय रूप से तैयार") }),

  page("track", "tracking", "status", "Track", "ट्रैक", "Track a demo report", "डेमो रिपोर्ट ट्रैक करें", "Use the documented synthetic reference only.", "केवल दिए गए सिंथेटिक संदर्भ का उपयोग करें।", { sources: ["officialTrack"] }),

  page("official-tools", "suspect", "hub", "Suspect and abuse tools", "संदिग्ध और दुरुपयोग उपकरण", "Check, document, and understand suspicious activity", "संदिग्ध गतिविधि जाँचें, दर्ज करें और समझें", "These local tools demonstrate the questions official services may ask without contacting them.", "ये स्थानीय उपकरण आधिकारिक सेवाओं से संपर्क किए बिना संभावित प्रश्नों का अभ्यास कराते हैं।", {
    sources: ["officialSuspectSearch", "officialSuspectWebsite", "officialSuspectReport", "officialReportAbuse", "officialTafcop", "officialGac"], items: [
      item("Check an identifier", "पहचानकर्ता जाँचें", "Try a synthetic mobile, email, account, or social handle.", "सिंथेटिक मोबाइल, ईमेल, खाता या सोशल हैंडल जाँचें।", "check-identifier"),
      item("Check a website or app", "वेबसाइट या ऐप जाँचें", "Review a fictional URL against a deterministic fixture.", "काल्पनिक URL को निश्चित फ़िक्स्चर से जाँचें।", "check-website"),
      item("Report a suspect", "संदिग्ध रिपोर्ट करें", "Prepare a local suspect-information draft.", "स्थानीय संदिग्ध-सूचना मसौदा तैयार करें।", "report-suspect"),
      item("Social-platform abuse", "सोशल प्लेटफ़ॉर्म दुरुपयोग", "Find safe evidence steps and platform categories.", "सुरक्षित साक्ष्य चरण और प्लेटफ़ॉर्म श्रेणियाँ देखें।", "report-abuse"),
      item("Mobile connections", "मोबाइल कनेक्शन", "Understand a TAFCOP-style check through synthetic data.", "सिंथेटिक डेटा से TAFCOP-जैसी जाँच समझें।", "mobile-connections"),
      item("Appeal guidance", "अपील मार्गदर्शन", "Prepare an illustrative grievance appeal.", "एक उदाहरणात्मक शिकायत अपील तैयार करें।", "appeal")
    ]
  }),
  page("check-identifier", "suspect", "form", "Identifier check", "पहचानकर्ता जाँच", "Check a synthetic identifier", "सिंथेटिक पहचानकर्ता जाँचें", "This deterministic check recognises demo@example.test only.", "यह निश्चित जाँच केवल demo@example.test को पहचानती है।", { fields: [field("identifierType", "select", "Identifier type", "पहचानकर्ता प्रकार", { required: true, options: [bi("Email", "ईमेल"), bi("Mobile", "मोबाइल"), bi("Account", "खाता"), bi("Social handle", "सोशल हैंडल")] }), field("identifier", "text", "Synthetic identifier", "सिंथेटिक पहचानकर्ता", { required: true, pattern: "^demo@example\\.test$", example: "demo@example.test" })], sources: ["officialSuspectSearch"], result: bi("Illustrative match found in the local demo fixture", "स्थानीय डेमो फ़िक्स्चर में उदाहरणात्मक मिलान मिला") }),
  page("check-website", "suspect", "form", "Website and app check", "वेबसाइट और ऐप जाँच", "Check a synthetic website or app", "सिंथेटिक वेबसाइट या ऐप जाँचें", "The example URL is fictional and never requested over the network.", "उदाहरण URL काल्पनिक है और नेटवर्क पर अनुरोधित नहीं होता।", { fields: [field("website", "url", "Synthetic URL", "सिंथेटिक URL", { required: true, pattern: "^https://example\\.test/?$", example: "https://example.test" })], sources: ["officialSuspectWebsite"], result: bi("Illustrative caution record found", "उदाहरणात्मक सावधानी रिकॉर्ड मिला") }),
  page("report-suspect", "suspect", "form", "Suspect report", "संदिग्ध रिपोर्ट", "Prepare suspect information", "संदिग्ध जानकारी तैयार करें", "Record only fictional identifiers and observations.", "केवल काल्पनिक पहचानकर्ता और अवलोकन दर्ज करें।", { fields: [field("identifier", "text", "Synthetic identifier", "सिंथेटिक पहचानकर्ता", { required: true, example: "demo@example.test" }), field("description", "textarea", "What made it suspicious?", "यह संदिग्ध क्यों लगा?", { required: true, minLength: 24 })], sources: ["officialSuspectReport"], result: bi("Suspect-information draft prepared locally", "संदिग्ध-सूचना मसौदा स्थानीय रूप से तैयार") }),
  page("report-abuse", "suspect", "directory", "Social-platform abuse", "सोशल-प्लेटफ़ॉर्म दुरुपयोग", "Report abuse without losing evidence", "साक्ष्य खोए बिना दुरुपयोग रिपोर्ट करें", "Preserve the profile URL, timestamps, message context, and screenshots before blocking or reporting.", "ब्लॉक या रिपोर्ट करने से पहले प्रोफ़ाइल URL, समय, संदेश संदर्भ और स्क्रीनशॉट सुरक्षित रखें।", { sources: ["officialReportAbuse"], items: [item("Preserve", "सुरक्षित रखें", "Capture the full context, not only one message.", "केवल एक संदेश नहीं, पूरा संदर्भ रखें।"), item("Use platform tools", "प्लेटफ़ॉर्म उपकरण", "Choose impersonation, threats, fraud, or harassment accurately.", "प्रतिरूपण, धमकी, धोखाधड़ी या उत्पीड़न सही चुनें।"), item("Prepare a complaint", "शिकायत तैयार करें", "Use the local complaint hub when the incident needs a fuller record.", "घटना के विस्तृत रिकॉर्ड के लिए स्थानीय शिकायत हब उपयोग करें।", "complaints")] }),
  page("mobile-connections", "suspect", "form", "Mobile connections", "मोबाइल कनेक्शन", "Review synthetic mobile connections", "सिंथेटिक मोबाइल कनेक्शन देखें", "This is an explanatory simulation, not TAFCOP and not a telecom lookup.", "यह व्याख्यात्मक सिमुलेशन है, TAFCOP या दूरसंचार खोज नहीं।", { fields: [field("mobile", "text", "Synthetic mobile number", "सिंथेटिक मोबाइल नंबर", { required: true, pattern: "^9000000000$", example: "9000000000" })], sources: ["officialTafcop"], result: bi("Two illustrative connections are shown in this demo", "इस डेमो में दो उदाहरणात्मक कनेक्शन दिखाए गए हैं") }),
  page("appeal", "suspect", "form", "Appeal practice", "अपील अभ्यास", "Prepare a synthetic appeal", "सिंथेटिक अपील तैयार करें", "This does not file an appeal with GAC or any platform.", "यह GAC या किसी प्लेटफ़ॉर्म पर अपील दर्ज नहीं करता।", { fields: [field("reference", "text", "Synthetic grievance reference", "सिंथेटिक शिकायत संदर्भ", { required: true, pattern: "^APPEAL-DEMO-001$", example: "APPEAL-DEMO-001" }), field("reason", "textarea", "Why should it be reconsidered?", "पुनर्विचार क्यों होना चाहिए?", { required: true, minLength: 24 })], sources: ["officialGac"], result: bi("Appeal draft prepared locally", "अपील मसौदा स्थानीय रूप से तैयार") }),

  page("volunteers", "volunteers", "hub", "Cyber Volunteers", "साइबर स्वयंसेवक", "Understand the Cyber Volunteer pathway", "साइबर स्वयंसेवक मार्ग समझें", "Explore the public programme information and practise registration without creating an account.", "खाता बनाए बिना सार्वजनिक कार्यक्रम जानकारी और पंजीकरण अभ्यास देखें।", { sources: ["officialVolunteerConcept", "officialVolunteerInstructions"], items: [item("Programme overview", "कार्यक्रम परिचय", "Understand scope, responsibilities, and boundaries.", "दायरा, जिम्मेदारियाँ और सीमाएँ समझें।", "volunteer-terms"), item("Unlawful-content guidance", "गैरकानूनी सामग्री मार्गदर्शन", "Learn what to preserve and how to avoid resharing harm.", "क्या सुरक्षित रखें और हानिकारक सामग्री दोबारा साझा न करें।", "unlawful-content"), item("Registration practice", "पंजीकरण अभ्यास", "Complete a synthetic interest form.", "सिंथेटिक रुचि फ़ॉर्म भरें।", "volunteer-register"), item("Login practice", "लॉगिन अभ्यास", "Use a deterministic demo identity.", "निश्चित डेमो पहचान का उपयोग करें।", "volunteer-login")] }),
  page("volunteer-terms", "volunteers", "guidance", "Volunteer terms", "स्वयंसेवक नियम", "Volunteer responsibilities and limits", "स्वयंसेवक जिम्मेदारियाँ और सीमाएँ", "Participation does not grant investigative authority. Volunteers should follow official terms and protect personal data.", "भागीदारी से जाँच अधिकार नहीं मिलता। स्वयंसेवकों को आधिकारिक नियम और व्यक्तिगत डेटा सुरक्षा का पालन करना चाहिए।", { sources: ["officialVolunteerTerms", "officialVolunteerInstructions"], items: [item("No authority claim", "अधिकार का दावा नहीं", "Do not impersonate police or government personnel.", "पुलिस या सरकारी कर्मी का प्रतिरूपण न करें।"), item("Protect privacy", "गोपनीयता रखें", "Do not collect or publish victim information.", "पीड़ित की जानकारी एकत्र या प्रकाशित न करें।"), item("Use official definitions", "आधिकारिक परिभाषाएँ", "Check current programme terms before real participation.", "वास्तविक भागीदारी से पहले वर्तमान कार्यक्रम नियम देखें।")] }),
  page("unlawful-content", "volunteers", "guidance", "Unlawful content", "गैरकानूनी सामग्री", "Handle potentially unlawful content carefully", "संभावित गैरकानूनी सामग्री सावधानी से संभालें", "Record the URL and context without downloading, forwarding, or amplifying harmful material.", "हानिकारक सामग्री डाउनलोड, अग्रेषित या प्रसारित किए बिना URL और संदर्भ दर्ज करें।", { sources: ["officialVolunteerUnlawful"], items: [item("Minimise handling", "कम से कम संभालें", "Do not save more material than is necessary to identify the source.", "स्रोत पहचानने के लिए आवश्यक से अधिक सामग्री न रखें।"), item("Preserve context", "संदर्भ सुरक्षित रखें", "Record the page URL, account, date, and time.", "पेज URL, खाता, तारीख और समय दर्ज करें।"), item("Use official reporting", "आधिकारिक रिपोर्टिंग", "Follow the current official instructions for real reports.", "वास्तविक रिपोर्ट के लिए वर्तमान आधिकारिक निर्देशों का पालन करें।")] }),
  page("volunteer-register", "volunteers", "form", "Volunteer registration", "स्वयंसेवक पंजीकरण", "Practise a volunteer registration", "स्वयंसेवक पंजीकरण का अभ्यास करें", "No account is created and no personal data is retained.", "कोई खाता नहीं बनता और व्यक्तिगत डेटा नहीं रखा जाता।", { fields: [field("fullName", "text", "Synthetic name", "सिंथेटिक नाम", { required: true, example: "Demo Volunteer" }), field("region", "text", "Synthetic region", "सिंथेटिक क्षेत्र", { required: true, example: "Demo District" }), field("interest", "select", "Area of interest", "रुचि क्षेत्र", { required: true, options: [bi("Awareness", "जागरूकता"), bi("Content reporting", "सामग्री रिपोर्टिंग"), bi("Community support", "सामुदायिक सहायता")] })], sources: ["officialVolunteerConcept", "officialVolunteerInstructions"], result: bi("Volunteer interest draft prepared locally", "स्वयंसेवक रुचि मसौदा स्थानीय रूप से तैयार") }),
  page("volunteer-login", "volunteers", "form", "Volunteer login", "स्वयंसेवक लॉगिन", "Open the synthetic volunteer area", "सिंथेटिक स्वयंसेवक क्षेत्र खोलें", "Use VOL-DEMO-001 and demo-only. This is not authentication.", "VOL-DEMO-001 और demo-only उपयोग करें। यह प्रमाणीकरण नहीं है।", { fields: [field("volunteerId", "text", "Demo volunteer ID", "डेमो स्वयंसेवक आईडी", { required: true, pattern: "^VOL-DEMO-001$", example: "VOL-DEMO-001" }), field("password", "password", "Demo password", "डेमो पासवर्ड", { required: true, pattern: "^demo-only$", example: "demo-only" })], sources: ["officialVolunteerLogin"], result: bi("Synthetic volunteer area ready", "सिंथेटिक स्वयंसेवक क्षेत्र तैयार") }),

  page("learning-corner", "learning", "hub", "Learning Corner", "लर्निंग कॉर्नर", "Learn, prepare, and stay safer online", "सीखें, तैयारी करें और ऑनलाइन सुरक्षित रहें", "Browse concise local guides based on audited public resources.", "ऑडिट किए गए सार्वजनिक संसाधनों पर आधारित संक्षिप्त स्थानीय मार्गदर्शिकाएँ देखें।", { sources: ["officialManuals", "officialFaq", "officialAdvisories"], items: [item("Citizen manuals", "नागरिक पुस्तिकाएँ", "Plain-language reporting preparation.", "सरल भाषा में रिपोर्टिंग तैयारी।", "guides"), item("FAQ", "सामान्य प्रश्न", "Answers about evidence, timing, and safe next steps.", "साक्ष्य, समय और सुरक्षित अगले कदमों के उत्तर।", "faq"), item("Advisories", "सलाह", "Recognise current scam patterns.", "वर्तमान घोटाला पैटर्न पहचानें।", "advisories"), item("Safety", "सुरक्षा", "Practical account and payment protection.", "व्यावहारिक खाता और भुगतान सुरक्षा।", "safety"), item("Awareness", "जागरूकता", "Shareable prevention guidance.", "साझा करने योग्य रोकथाम मार्गदर्शन।", "awareness"), item("Daily digest", "दैनिक डाइजेस्ट", "A structured advisory reading list.", "संरचित सलाह पढ़ने की सूची।", "daily-digest"), item("Training", "प्रशिक्षण", "Learning paths for citizens and facilitators.", "नागरिकों और सहायकों के सीखने के मार्ग।", "training"), item("Media", "मीडिया", "Video, radio, and gallery directory.", "वीडियो, रेडियो और गैलरी निर्देशिका।", "media"), item("Accessibility", "सुगम्यता", "Keyboard and screen-reader guidance.", "कीबोर्ड और स्क्रीन-रीडर मार्गदर्शन।", "accessibility")] }),
  page("guides", "learning", "guidance", "Citizen manuals", "नागरिक पुस्तिकाएँ", "Prepare before you report", "रिपोर्ट से पहले तैयारी करें", "Collect transaction facts, preserve evidence, and write a clear chronology.", "लेन-देन तथ्य, साक्ष्य और स्पष्ट घटनाक्रम तैयार करें।", { sources: ["officialManuals"], items: [item("Record identifiers", "पहचानकर्ता दर्ज करें", "Keep UTR, account, phone, email, profile, and URL details.", "UTR, खाता, फोन, ईमेल, प्रोफ़ाइल और URL विवरण रखें।"), item("Preserve originals", "मूल सुरक्षित रखें", "Keep original files and note when each item was received.", "मूल फ़ाइलें और प्राप्ति समय सुरक्षित रखें।"), item("Write a timeline", "घटनाक्रम लिखें", "Order messages, clicks, payments, and follow-up actions.", "संदेश, क्लिक, भुगतान और बाद की कार्रवाई क्रम में रखें।")] }),
  page("advisories", "learning", "directory", "Advisories", "सलाह", "Recognise common fraud patterns", "सामान्य धोखाधड़ी पैटर्न पहचानें", "Review phishing, payment fraud, and impersonation cues without sensational imagery.", "सनसनीखेज चित्रों के बिना फ़िशिंग, भुगतान धोखाधड़ी और प्रतिरूपण संकेत देखें।", { sources: ["officialAdvisories", "officialFakeEmailAlert"], items: [item("Phishing", "फ़िशिंग", "Unexpected links, urgency, and credential requests are warning signs.", "अनपेक्षित लिंक, जल्दबाज़ी और पहचान जानकारी माँगना चेतावनी संकेत हैं।"), item("Payment fraud", "भुगतान धोखाधड़ी", "Verify the recipient and purpose before authorising a payment.", "भुगतान से पहले प्राप्तकर्ता और उद्देश्य सत्यापित करें।"), item("Impersonation", "प्रतिरूपण", "Confirm unusual requests through a separate trusted channel.", "असामान्य अनुरोध अलग विश्वसनीय माध्यम से सत्यापित करें।")] }),
  page("safety", "learning", "guidance", "Online safety", "ऑनलाइन सुरक्षा", "Small habits that reduce risk", "जोखिम घटाने वाली छोटी आदतें", "Use unique passwords, protect recovery channels, and pause before urgent transfers.", "अलग पासवर्ड रखें, रिकवरी माध्यम सुरक्षित करें और जल्दबाज़ी वाले भुगतान से पहले रुकें।", { sources: ["officialSafety"], items: [item("Secure accounts", "खाते सुरक्षित करें", "Use multi-factor authentication where available.", "जहाँ उपलब्ध हो बहु-कारक प्रमाणीकरण उपयोग करें।"), item("Verify independently", "स्वतंत्र सत्यापन", "Use a known number or official app, not the message link.", "संदेश लिंक नहीं, ज्ञात नंबर या आधिकारिक ऐप उपयोग करें।"), item("Act quickly after fraud", "धोखाधड़ी के बाद जल्दी करें", "For financial cyber fraud in India, call 1930 and use cybercrime.gov.in.", "भारत में वित्तीय साइबर धोखाधड़ी के लिए 1930 पर कॉल करें और cybercrime.gov.in उपयोग करें।")] }),
  page("awareness", "learning", "guidance", "Awareness", "जागरूकता", "Help others recognise manipulation", "दूसरों को छल पहचानने में मदद करें", "Share verified prevention guidance without forwarding suspicious links or private evidence.", "संदिग्ध लिंक या निजी साक्ष्य साझा किए बिना सत्यापित रोकथाम मार्गदर्शन साझा करें।", { sources: ["officialAwareness"], items: [item("Pause", "रुकें", "Urgency is often used to prevent verification.", "जल्दबाज़ी अक्सर सत्यापन रोकने के लिए बनाई जाती है।"), item("Verify", "सत्यापित करें", "Contact the organisation through a known channel.", "ज्ञात माध्यम से संस्था से संपर्क करें।"), item("Protect", "सुरक्षित रखें", "Never share OTPs, PINs, or recovery codes.", "OTP, PIN या रिकवरी कोड साझा न करें।")] }),
  page("daily-digest", "learning", "directory", "Daily digest", "दैनिक डाइजेस्ट", "A calmer way to review advisories", "सलाह देखने का सरल तरीका", "Use this local reading structure; verify dates and notices in the cited official source.", "इस स्थानीय पढ़ने की संरचना का उपयोग करें; तारीख और सूचना आधिकारिक स्रोत में सत्यापित करें।", { sources: ["officialDigest"], items: [item("Payment requests", "भुगतान अनुरोध", "Check recent payment-fraud patterns.", "नए भुगतान धोखाधड़ी पैटर्न देखें।", "advisories"), item("Account safety", "खाता सुरक्षा", "Review practical protective steps.", "व्यावहारिक सुरक्षा चरण देखें।", "safety"), item("Evidence readiness", "साक्ष्य तैयारी", "Prepare before an incident becomes harder to reconstruct.", "घटना का पुनर्निर्माण कठिन होने से पहले तैयारी करें।", "guides")] }),
  page("training", "learning", "directory", "Training", "प्रशिक्षण", "Structured learning paths", "संरचित सीखने के मार्ग", "Choose a citizen, family, or community-facilitator path.", "नागरिक, परिवार या सामुदायिक सहायक मार्ग चुनें।", { sources: ["officialTraining"], items: [item("Citizen basics", "नागरिक आधार", "Recognise fraud and preserve essential evidence.", "धोखाधड़ी पहचानें और आवश्यक साक्ष्य रखें।", "safety"), item("Family support", "परिवार सहायता", "Help someone act without blame or panic.", "बिना दोष या घबराहट के किसी की मदद करें।", "faq"), item("Facilitator path", "सहायक मार्ग", "Use plain language and respect privacy boundaries.", "सरल भाषा और गोपनीयता सीमाओं का पालन करें।", "volunteer-terms")] }),
  page("media", "learning", "directory", "Media library", "मीडिया लाइब्रेरी", "Videos, radio, and visual learning", "वीडियो, रेडियो और दृश्य सीखना", "Browse a local directory, then use the Sources panel only when you intentionally want the official collections.", "स्थानीय निर्देशिका देखें; आधिकारिक संग्रह के लिए केवल स्रोत पैनल उपयोग करें।", { sources: ["officialVideos", "officialRadio", "officialPhotos"], items: [item("Video guidance", "वीडियो मार्गदर्शन", "Short explainers for reporting and safety.", "रिपोर्टिंग और सुरक्षा के छोटे विवरण।"), item("Radio messages", "रेडियो संदेश", "Audio awareness material and campaign messages.", "ऑडियो जागरूकता सामग्री और अभियान संदेश।"), item("Photo gallery", "फोटो गैलरी", "Public-event and awareness imagery.", "सार्वजनिक कार्यक्रम और जागरूकता चित्र।")] }),
  page("accessibility", "learning", "guidance", "Accessibility", "सुगम्यता", "Use the portal with keyboard and assistive technology", "कीबोर्ड और सहायक तकनीक से पोर्टल उपयोग करें", "All interactive controls use visible focus and the service works without a mouse.", "सभी इंटरैक्टिव नियंत्रण में स्पष्ट फोकस है और सेवा माउस के बिना चलती है।", { sources: ["officialScreenReader"], items: [item("Keyboard", "कीबोर्ड", "Use Tab and Shift+Tab to move; Enter or Space activates controls.", "आगे-पीछे जाने के लिए Tab और Shift+Tab, सक्रिय करने के लिए Enter या Space उपयोग करें।"), item("Headings", "शीर्षक", "Each page has one main heading and ordered sections.", "हर पेज में एक मुख्य शीर्षक और क्रमबद्ध अनुभाग हैं।"), item("Errors", "त्रुटियाँ", "Form errors move focus to a linked summary.", "फ़ॉर्म त्रुटि पर फोकस लिंक किए गए सारांश पर जाता है।")] }),

  page("faq", "help", "guidance", "FAQ", "सामान्य प्रश्न", "Questions citizens ask before reporting", "रिपोर्ट से पहले नागरिकों के प्रश्न", "Clear answers about evidence, synthetic data, and official next steps.", "साक्ष्य, सिंथेटिक डेटा और आधिकारिक अगले कदमों के स्पष्ट उत्तर।", { sources: ["officialFaq"], items: [item("Does this submit a complaint?", "क्या यह शिकायत जमा करता है?", "No. It prepares synthetic information locally and never contacts NCRP.", "नहीं। यह स्थानीय रूप से सिंथेटिक जानकारी तैयार करता है और NCRP से संपर्क नहीं करता।"), item("Can I continue without every file?", "क्या हर फ़ाइल के बिना आगे बढ़ सकते हैं?", "Yes. Mark missing evidence and preserve what is available.", "हाँ। गायब साक्ष्य चिन्हित करें और उपलब्ध सामग्री सुरक्षित रखें।"), item("What should I do after financial fraud?", "वित्तीय धोखाधड़ी के बाद क्या करें?", "Call 1930 manually and use cybercrime.gov.in as soon as possible.", "जितनी जल्दी हो 1930 पर स्वयं कॉल करें और cybercrime.gov.in उपयोग करें।")] }),
  page("contact", "help", "directory", "Contact", "संपर्क", "Find the right kind of help", "सही प्रकार की मदद खोजें", "Use local guidance first; official nodal and grievance details remain in the Sources panel.", "पहले स्थानीय मार्गदर्शन उपयोग करें; आधिकारिक नोडल और शिकायत विवरण स्रोत पैनल में हैं।", { sources: ["officialContacts"], items: [item("Financial fraud", "वित्तीय धोखाधड़ी", "Call 1930 manually and prepare the transaction evidence.", "1930 पर स्वयं कॉल करें और लेन-देन साक्ष्य तैयार करें।", "act-now"), item("Portal feedback", "पोर्टल प्रतिक्रिया", "Send feedback to this local simulation.", "इस स्थानीय सिमुलेशन को प्रतिक्रिया दें।", "feedback"), item("Grievance guidance", "शिकायत मार्गदर्शन", "Understand escalation and public notices.", "एस्केलेशन और सार्वजनिक सूचना समझें।", "grievance")] }),
  page("feedback", "help", "form", "Feedback", "प्रतिक्रिया", "Share feedback about this concept", "इस कॉन्सेप्ट पर प्रतिक्रिया दें", "Feedback stays in memory and disappears on reload.", "प्रतिक्रिया मेमोरी में रहती है और रीलोड पर मिट जाती है।", { fields: [field("topic", "select", "Topic", "विषय", { required: true, options: [bi("Navigation", "नेविगेशन"), bi("Reporting flow", "रिपोर्टिंग प्रवाह"), bi("Learning content", "सीखने की सामग्री"), bi("Accessibility", "सुगम्यता")] }), field("rating", "select", "Rating", "रेटिंग", { required: true, options: [bi("Needs work", "सुधार चाहिए"), bi("Useful", "उपयोगी"), bi("Very clear", "बहुत स्पष्ट")] }), field("message", "textarea", "Feedback", "प्रतिक्रिया", { required: true, minLength: 12 })], sources: ["officialFeedback"], result: bi("Feedback recorded for this session", "इस सत्र के लिए प्रतिक्रिया दर्ज") }),
  page("grievance", "help", "legal", "Grievance guidance", "शिकायत मार्गदर्शन", "Understand grievance and escalation routes", "शिकायत और एस्केलेशन मार्ग समझें", "Different issues belong to different systems. Read the notice and verify the destination before sharing information.", "अलग मुद्दे अलग प्रणालियों से संबंधित हैं। जानकारी साझा करने से पहले सूचना और गंतव्य सत्यापित करें।", { sources: ["officialContacts", "officialCpgramsNotice"], items: [item("Portal complaint", "पोर्टल शिकायत", "Use the current NCRP nodal or grievance contact listed by the official portal.", "आधिकारिक पोर्टल पर वर्तमान NCRP नोडल या शिकायत संपर्क देखें।"), item("Government grievance", "सरकारी शिकायत", "CPGRAMS scope may differ from cybercrime reporting.", "CPGRAMS का दायरा साइबर अपराध रिपोर्टिंग से अलग हो सकता है।"), item("Keep a record", "रिकॉर्ड रखें", "Save acknowledgement, date, destination, and response.", "पावती, तारीख, गंतव्य और उत्तर सुरक्षित रखें।")] }),
  page("policies", "legal", "legal", "Website policy", "वेबसाइट नीति", "How this local concept behaves", "यह स्थानीय कॉन्सेप्ट कैसे काम करता है", "The site has no accounts, analytics, storage, uploads, or network submission.", "इस साइट में खाता, एनालिटिक्स, स्टोरेज, अपलोड या नेटवर्क सबमिशन नहीं है।", { sources: ["officialPolicies"], items: [item("Local operation", "स्थानीय संचालन", "All interactions run in the browser.", "सभी इंटरैक्शन ब्राउज़र में चलते हैं।"), item("No persistence", "कोई स्थायित्व नहीं", "Reloading resets every synthetic form and result.", "रीलोड करने पर हर सिंथेटिक फ़ॉर्म और परिणाम रीसेट होता है।"), item("Source transparency", "स्रोत पारदर्शिता", "Official URLs appear only in labelled Sources panels and the footer.", "आधिकारिक URL केवल स्रोत पैनल और फुटर में दिखाई देते हैं।")] }),
  page("privacy", "legal", "legal", "Privacy", "गोपनीयता", "Do not enter real personal information", "वास्तविक व्यक्तिगत जानकारी न भरें", "The application keeps temporary form state in JavaScript memory only.", "एप्लिकेशन अस्थायी फ़ॉर्म स्थिति केवल जावास्क्रिप्ट मेमोरी में रखता है।", { sources: ["officialPrivacy"], items: [item("Synthetic data only", "केवल सिंथेटिक डेटा", "Use the supplied examples rather than real details.", "वास्तविक विवरण के बजाय दिए गए उदाहरण उपयोग करें।"), item("No upload", "कोई अपलोड नहीं", "Evidence controls are readiness choices, not file inputs.", "साक्ष्य नियंत्रण तैयारी विकल्प हैं, फ़ाइल इनपुट नहीं।"), item("Reset on reload", "रीलोड पर रीसेट", "Nothing is intentionally persisted by the application.", "एप्लिकेशन जानबूझकर कुछ भी स्थायी नहीं रखता।")] }),
  page("disclaimer", "legal", "legal", "Disclaimer", "अस्वीकरण", "Independent concept, not a government service", "स्वतंत्र कॉन्सेप्ट, सरकारी सेवा नहीं", "This prototype does not represent NCRP, police, banks, telecom providers, or social platforms.", "यह प्रोटोटाइप NCRP, पुलिस, बैंक, दूरसंचार प्रदाता या सोशल प्लेटफ़ॉर्म का प्रतिनिधित्व नहीं करता।", { sources: ["officialDisclaimer"], items: [item("No submission", "कोई सबमिशन नहीं", "No complaint, report, appeal, feedback, or registration leaves the app.", "कोई शिकायत, रिपोर्ट, अपील, प्रतिक्रिया या पंजीकरण ऐप से बाहर नहीं जाता।"), item("No status claim", "कोई स्थिति दावा नहीं", "All references, matches, and outcomes are illustrative.", "सभी संदर्भ, मिलान और परिणाम उदाहरणात्मक हैं।"), item("Official action", "आधिकारिक कार्रवाई", "For real financial fraud, call 1930 and use cybercrime.gov.in.", "वास्तविक वित्तीय धोखाधड़ी के लिए 1930 पर कॉल करें और cybercrime.gov.in उपयोग करें।")] }),
  page("notices", "legal", "legal", "Public notices", "सार्वजनिक सूचनाएँ", "RTI and CPGRAMS notices", "RTI और CPGRAMS सूचनाएँ", "These summaries help route readers to the right source; the cited PDFs remain authoritative.", "ये सारांश पाठक को सही स्रोत तक पहुँचाते हैं; उद्धृत PDF प्रामाणिक हैं।", { sources: ["officialRtiNotice", "officialCpgramsNotice"], items: [item("RTI notice", "RTI सूचना", "Read the current official notice before sending an RTI request.", "RTI अनुरोध भेजने से पहले वर्तमान आधिकारिक सूचना पढ़ें।"), item("CPGRAMS notice", "CPGRAMS सूचना", "Check whether the grievance belongs in CPGRAMS or a cybercrime channel.", "जाँचें कि शिकायत CPGRAMS या साइबर अपराध माध्यम की है।"), item("Date matters", "तारीख महत्वपूर्ण है", "Notices can change; verify the source before acting.", "सूचनाएँ बदल सकती हैं; कार्रवाई से पहले स्रोत सत्यापित करें।")] }),
  page("about", "legal", "legal", "About", "परिचय", "A calmer way to prepare cybercrime information", "साइबर अपराध जानकारी तैयार करने का सरल तरीका", "This independent prototype reorganises audited public-service information into a bilingual, accessible, local experience.", "यह स्वतंत्र प्रोटोटाइप ऑडिट की गई सार्वजनिक-सेवा जानकारी को द्विभाषी, सुगम और स्थानीय अनुभव में व्यवस्थित करता है।", { sources: ["officialHome"], items: [item("Purpose", "उद्देश्य", "Reduce confusion before a citizen reaches an official service.", "नागरिक के आधिकारिक सेवा तक पहुँचने से पहले भ्रम घटाएँ।"), item("Scope", "दायरा", "Financial-fraud preparation plus public information simulations.", "वित्तीय धोखाधड़ी तैयारी और सार्वजनिक जानकारी सिमुलेशन।"), item("Boundary", "सीमा", "No government integration, identity, or authority claim.", "कोई सरकारी एकीकरण, पहचान या अधिकार दावा नहीं।") ] })
]);

export const CONTENT_ROUTES = Object.freeze(PORTAL_ROUTES.map((route) => route.id));
export const ROUTE_BY_ID = Object.freeze(Object.fromEntries(PORTAL_ROUTES.map((route) => [route.id, route])));
export const ROUTE_GROUPS = Object.freeze([...new Set(PORTAL_ROUTES.map((route) => route.group))]);

export function localizeRoute(route, language = "en") {
  if (!route) return null;
  const localize = (value) => value?.[language] || value?.en || "";
  return {
    ...route,
    label: localize(route.label), eyebrow: localize(route.eyebrow), title: localize(route.title), intro: localize(route.intro),
    result: localize(route.result),
    items: route.items.map((entry) => ({ ...entry, title: localize(entry.title), body: localize(entry.body) })),
    fields: route.fields.map((entry) => ({ ...entry, label: localize(entry.label), options: entry.options?.map(localize) || [] }))
  };
}
