"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useMemo, useRef, useState } from "react";
import { CheckCircle2, ExternalLink, SearchCheck, TriangleAlert, Waypoints } from "lucide-react";
import { CHECK_MODES, normalizeCheckMode, resolveCheckOutcome, type CheckMode, type CheckOutcome } from "@/features/check";
import { routeDefinition } from "@/lib/routes";
import { OFFICIAL_DESTINATIONS } from "@/data/official-sources";
import { createServiceRecord, validateServiceValues, type ServiceRecord } from "@/domains/report/service-form";
import { usePortal } from "./portal-provider";

const MODE_ROUTES: Record<Exclude<CheckMode, "overview">, string> = {
  identifier: "check-identifier", website: "check-website", mobile: "mobile-connections", abuse: "report-abuse", suspect: "report-suspect", appeal: "appeal"
};

export function CheckWorkspace() {
  const { language } = usePortal();
  const router = useRouter();
  const params = useSearchParams();
  const mode = normalizeCheckMode(params.get("mode"));
  const setMode = (next: CheckMode) => router.replace(next === "overview" ? "/official-tools" : `/official-tools?mode=${next}`);
  return <div className="mx-auto max-w-content px-5 py-8 md:px-8 md:py-10">
    <nav aria-label="Breadcrumb" className="text-xs text-civic-700"><Link className="inline-flex min-h-11 min-w-11 items-center justify-center" href="/">{language === "hi" ? "होम" : "Home"}</Link><span className="mx-2">/</span><span aria-current="page">{language === "hi" ? "जाँच" : "Check"}</span></nav>
    <header className="mt-5 grid gap-6 border-b border-line pb-8 lg:grid-cols-[1fr_340px] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-civic-700">{language === "hi" ? "स्थानीय डेमो उपकरण" : "Local demo tools"}</p><h1 className="mt-3 max-w-[18ch] text-[38px] font-semibold leading-[1.08] tracking-[-0.035em] sm:text-[44px]">{language === "hi" ? "संदिग्ध विवरण जाँचें और अगला कदम तैयार करें" : "Check suspicious details and prepare the next step"}</h1><p className="mt-4 max-w-3xl leading-7 text-muted">{language === "hi" ? "निश्चित डेमो रिकॉर्ड से जाँचें। कुछ भी भेजा, अपलोड या ब्राउज़र में सहेजा नहीं जाता।" : "Use fixed demo records to practise a check. Nothing is sent, uploaded, or saved by this workspace."}</p></div><div className="rounded-panel bg-civic-50 p-5"><Waypoints className="size-7 text-civic-700" /><p className="mt-3 text-sm leading-6 text-muted">{language === "hi" ? "वास्तविक जाँच या कार्रवाई के लिए परिणाम के साथ दिया गया आधिकारिक गंतव्य खोलें।" : "For a real check or action, use the verified official destination shown with the result."}</p></div></header>
    <nav className="mt-6 flex gap-2 overflow-x-auto pb-1" aria-label={language === "hi" ? "जाँच उपकरण" : "Check tools"}>{CHECK_MODES.map((entry) => <button key={entry} type="button" aria-current={entry === mode ? "page" : undefined} onClick={() => setMode(entry)} className={`min-h-11 shrink-0 rounded-control border px-4 text-sm font-semibold capitalize ${entry === mode ? "border-civic-600 bg-civic-50 text-civic-700" : "border-line bg-white"}`}>{modeLabel(entry, language)}</button>)}</nav>
    <section className="mt-7" data-check-mode={mode}>{mode === "overview" || mode === "identifier" || mode === "website" ? <IdentifierCheck mode={mode} setMode={setMode} /> : mode === "abuse" ? <AbuseMode /> : <LocalDraft mode={mode} />}</section>
  </div>;
}

function IdentifierCheck({ mode, setMode }: { mode: "overview" | "identifier" | "website"; setMode: (mode: CheckMode) => void }) {
  const { language } = usePortal();
  const [value, setValue] = useState("");
  const [outcome, setOutcome] = useState<CheckOutcome | null>(null);
  const inferred = resolveCheckOutcome(value, mode).detectedType;
  const suggestedMode = inferred === "url" ? "website" : "identifier";
  const submit = (event: FormEvent) => { event.preventDefault(); if (value.trim()) setOutcome(resolveCheckOutcome(value, mode === "overview" ? suggestedMode : mode)); };
  return <div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_340px]"><form onSubmit={submit} className="max-w-form rounded-panel border border-line bg-white p-5 sm:p-7"><h2 className="text-2xl font-semibold">{mode === "website" ? (language === "hi" ? "वेबसाइट या ऐप पता जाँचें" : "Check a website or app address") : (language === "hi" ? "संपर्क, खाता या पता जाँचें" : "Check a contact, account, or address")}</h2><label className="mt-5 grid gap-2 text-sm font-semibold"><span>{language === "hi" ? "केवल डेमो विवरण" : "Demo detail only"}</span><input required type={mode === "website" ? "url" : "text"} value={value} onChange={(event) => { setValue(event.target.value); setOutcome(null); }} className="min-h-11 rounded-control border border-line px-3 font-normal" placeholder={mode === "website" ? "https://example.test" : "demo@example.test"} /></label>{value && <div className="mt-4 rounded-control bg-civic-50 p-4 text-sm" aria-live="polite"><strong>{language === "hi" ? "यह ऐसा दिखता है:" : "Looks like:"}</strong> <span className="text-civic-700">{typeLabel(inferred, language)}</span>{mode === "overview" && inferred !== "unknown" && <button type="button" onClick={() => setMode(suggestedMode)} className="ml-3 min-h-11 font-semibold text-civic-700 underline underline-offset-4">{language === "hi" ? "इस जाँच का उपयोग करें" : `Use ${suggestedMode} check`}</button>}</div>}<p className="mt-4 text-xs leading-5 text-muted">{language === "hi" ? "डेमो मिलान: demo@example.test, demo@upi, 9000000000, 123456789012 या https://example.test" : "Demo matches: demo@example.test, demo@upi, 9000000000, 123456789012, or https://example.test"}</p><div className="mt-5 flex flex-wrap gap-3"><button className="min-h-11 rounded-control bg-civic-600 px-5 text-sm font-semibold text-white">{language === "hi" ? "डेमो जाँच चलाएँ" : "Run demo check"}</button><button type="button" onClick={() => { setValue(""); setOutcome(null); }} className="min-h-11 rounded-control border border-line px-5 text-sm font-semibold">{language === "hi" ? "रीसेट" : "Reset"}</button></div></form>{outcome ? <Outcome outcome={outcome} /> : <aside className="border-l-4 border-civic-600 bg-civic-50 p-5"><SearchCheck className="size-7 text-civic-700" /><h2 className="mt-4 text-lg font-semibold">{language === "hi" ? "परिणाम में क्या मिलेगा" : "What the result includes"}</h2><p className="mt-2 text-sm leading-6 text-muted">{language === "hi" ? "दिया गया डेमो मान, पहचाना प्रकार, मिलान स्थिति, उपयोगी जाँच, साक्ष्य और सही आधिकारिक लिंक।" : "The entered demo value, detected type, match status, useful checks, evidence, and the right official link."}</p></aside>}</div>;
}

function Outcome({ outcome }: { outcome: CheckOutcome }) {
  const { language } = usePortal();
  const destination = OFFICIAL_DESTINATIONS[outcome.destination];
  const matched = outcome.status === "match";
  return <aside className={`border-l-4 p-5 ${matched ? "border-success bg-success-soft" : "border-warning bg-warning-soft"}`} aria-live="polite">{matched ? <CheckCircle2 className="size-7 text-success" /> : <TriangleAlert className="size-7 text-warning" />}<h2 className="mt-4 text-xl font-semibold">{matched ? (language === "hi" ? "उदाहरणात्मक मिलान मिला" : "Illustrative match found") : (language === "hi" ? "डेमो मिलान नहीं मिला" : "No demo match found")}</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="font-semibold">{language === "hi" ? "दिया गया मान" : "Entered value"}</dt><dd className="mt-1 break-all text-muted">{outcome.value}</dd></div><div><dt className="font-semibold">{language === "hi" ? "पहचाना प्रकार" : "Detected type"}</dt><dd className="mt-1 text-muted">{typeLabel(outcome.detectedType, language)}</dd></div></dl>{!matched && <p className="mt-4 font-semibold text-warning">{language === "hi" ? "डेमो में अनुपस्थिति का अर्थ यह नहीं कि विवरण सुरक्षित है।" : "Absence from this demo does not mean the item is safe."}</p>}<div className="mt-5 border-t border-current/20 pt-4 text-sm leading-6"><p><strong>{language === "hi" ? "उपयोगी जाँच:" : "Useful checks:"}</strong> {language === "hi" ? "पता, वर्तनी, भुगतान माँग और संपर्क संदर्भ सत्यापित करें।" : "Verify the address, spelling, payment request, and contact context."}</p><p className="mt-2"><strong>{language === "hi" ? "उपयोगी साक्ष्य:" : "Useful evidence:"}</strong> {language === "hi" ? "मूल URL, संदेश, समय और भुगतान रिकॉर्ड सुरक्षित रखें।" : "Keep the original URL, messages, timestamps, and payment record."}</p></div><a href={destination.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-control bg-civic-600 px-4 text-sm font-semibold text-white">{destination[language]}<ExternalLink className="size-4" /></a></aside>;
}

function LocalDraft({ mode }: { mode: "mobile" | "suspect" | "appeal" }) {
  const { language } = usePortal();
  const route = routeDefinition(MODE_ROUTES[mode], language);
  const [record, setRecord] = useState<ServiceRecord>(() => createServiceRecord());
  const errorRef = useRef<HTMLDivElement>(null);
  const fields = route?.fields || [];
  const submit = (event: FormEvent) => { event.preventDefault(); const validation = validateServiceValues(fields, record.values, { required: language === "hi" ? "यह फ़ील्ड आवश्यक है।" : "This field is required.", short: language === "hi" ? "अधिक विवरण जोड़ें।" : "Add more detail.", invalid: language === "hi" ? "दिया गया डेमो उदाहरण उपयोग करें।" : "Use the documented demo example." }); setRecord({ values: validation.normalized, errors: validation.errors, submitted: !validation.errors.length }); if (validation.errors.length) requestAnimationFrame(() => errorRef.current?.focus()); };
  if (!route) return null;
  if (record.submitted) return <div className="max-w-form rounded-panel border border-success bg-success-soft p-6"><CheckCircle2 className="size-7 text-success" /><h2 className="mt-4 text-xl font-semibold">{route.result}</h2><p className="mt-2 text-sm text-muted">{language === "hi" ? "मसौदा केवल इस पेज की मेमोरी में है। कुछ भी भेजा या सहेजा नहीं गया।" : "The draft exists only in this page memory. Nothing was sent or stored."}</p><button onClick={() => setRecord(createServiceRecord())} className="mt-5 min-h-11 rounded-control border border-civic-600 px-5 text-sm font-semibold text-civic-700">{language === "hi" ? "विवरण बदलें" : "Edit details"}</button></div>;
  return <form onSubmit={submit} noValidate className="max-w-form rounded-panel border border-line bg-white p-5 sm:p-7"><h2 className="text-2xl font-semibold">{route.title}</h2><p className="mt-2 text-sm leading-6 text-muted">{route.intro}</p>{record.errors.length > 0 && <div ref={errorRef} tabIndex={-1} role="alert" className="mt-5 border-l-4 border-urgent bg-urgent-soft p-4"><h3 className="font-semibold text-urgent">{language === "hi" ? "चिह्नित फ़ील्ड जाँचें" : "Check the marked fields"}</h3></div>}<div className="mt-5 grid gap-5 sm:grid-cols-2">{fields.map((field) => <label key={field.name} className={`grid gap-2 text-sm font-semibold ${field.type === "textarea" ? "sm:col-span-2" : ""}`}><span>{field.label}</span>{field.type === "textarea" ? <textarea className="min-h-32 rounded-control border border-line p-3 font-normal" value={record.values[field.name] || ""} onChange={(event) => setRecord((old) => ({ ...old, values: { ...old.values, [field.name]: event.target.value }, errors: [] }))} /> : <input className="min-h-11 rounded-control border border-line px-3 font-normal" type={field.type} value={record.values[field.name] || ""} onChange={(event) => setRecord((old) => ({ ...old, values: { ...old.values, [field.name]: event.target.value }, errors: [] }))} />}{field.example && <span className="font-normal text-muted">{language === "hi" ? "डेमो उदाहरण" : "Demo example"}: <code>{field.example}</code></span>}</label>)}</div><div className="mt-5 flex gap-3"><button className="min-h-11 rounded-control bg-civic-600 px-5 text-sm font-semibold text-white">{language === "hi" ? "स्थानीय मसौदा तैयार करें" : "Prepare local draft"}</button><button type="button" onClick={() => setRecord(createServiceRecord())} className="min-h-11 rounded-control border border-line px-5 text-sm font-semibold">{language === "hi" ? "रीसेट" : "Reset"}</button></div></form>;
}

function AbuseMode() { const { language } = usePortal(); return <div className="max-w-document"><h2 className="text-2xl font-semibold">{language === "hi" ? "साक्ष्य खोए बिना प्लेटफ़ॉर्म दुरुपयोग रिपोर्ट करें" : "Report platform abuse without losing evidence"}</h2><ol className="mt-5 divide-y divide-line border-y border-line">{(language === "hi" ? [["सुरक्षित रखें", "मूल प्रोफ़ाइल URL, पूरा संदेश संदर्भ, समय और स्क्रीनशॉट रखें।"], ["सही श्रेणी चुनें", "प्रतिरूपण, धमकी, धोखाधड़ी या उत्पीड़न सही चुनें।"], ["आधिकारिक कार्रवाई", "प्लेटफ़ॉर्म उपकरण उपयोग करें; अपराध के लिए cybercrime.gov.in खोलें।"]] : [["Preserve", "Keep the original profile URL, full message context, timestamps, and screenshots."], ["Choose the right category", "Classify impersonation, threats, fraud, or harassment accurately."], ["Take official action", "Use the platform tools; for a crime, open cybercrime.gov.in."]]).map(([title, body], index) => <li key={title} className="grid gap-3 py-5 sm:grid-cols-[44px_1fr]"><span className="grid size-11 place-items-center rounded-full border border-civic-600 font-semibold text-civic-700">{index + 1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{body}</p></div></li>)}</ol><a className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-control bg-civic-600 px-5 text-sm font-semibold text-white" href={OFFICIAL_DESTINATIONS.officialReportAbuse.url} target="_blank" rel="noreferrer">{OFFICIAL_DESTINATIONS.officialReportAbuse[language]}<ExternalLink className="size-4" /></a></div>; }

function modeLabel(mode: CheckMode, language: "en" | "hi") { const labels = language === "hi" ? { overview: "सभी", identifier: "पहचानकर्ता", website: "वेबसाइट", mobile: "मोबाइल", abuse: "दुरुपयोग", suspect: "संदिग्ध मसौदा", appeal: "अपील" } : { overview: "Overview", identifier: "Identifier", website: "Website", mobile: "Mobile", abuse: "Abuse", suspect: "Suspect draft", appeal: "Appeal" }; return labels[mode]; }
function typeLabel(type: CheckOutcome["detectedType"], language: "en" | "hi") { const labels = language === "hi" ? { url: "वेब पता", email: "ईमेल", phone: "मोबाइल", upi: "UPI ID", "bank-account": "बैंक खाता", unknown: "अज्ञात" } : { url: "web address", email: "email", phone: "mobile", upi: "UPI ID", "bank-account": "bank account", unknown: "unknown" }; return labels[type]; }
