"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleHelp, FileCheck2, SearchCheck } from "lucide-react";
import { usePortal } from "./portal-provider";
import { ResponsiveIllustration } from "./responsive-illustration";

export function Home() {
  const { language, navigate, openAssistant } = usePortal();
  return <>
    <section className="bg-white"><div className="mx-auto grid max-w-content items-center gap-10 px-5 py-12 md:px-8 lg:grid-cols-[1fr_0.8fr] lg:py-16"><div><h1 className="max-w-[13ch] text-[44px] font-semibold leading-[1.04] tracking-[-0.04em] sm:text-[54px]">{language === "hi" ? "साइबर घटना को स्पष्ट रिपोर्ट तैयारी में बदलें" : "Turn a cyber incident into clear report preparation"}</h1><p className="mt-5 max-w-2xl text-[17px] leading-7 text-muted">{language === "hi" ? "जो हुआ उसे दर्ज करें, उपयोगी साक्ष्य को समयरेखा से जोड़ें और सही आधिकारिक अगले कदम तक जाएँ। ThreadZero सरकारी सेवा नहीं है।" : "Record what happened, connect useful evidence to the timeline, and reach the right official next step. ThreadZero is not a government service."}</p><div className="mt-7 flex flex-wrap gap-3"><button className="inline-flex min-h-11 items-center gap-2 rounded-control bg-civic-600 px-6 text-sm font-semibold text-white" onClick={() => navigate("incident")}>{language === "hi" ? "रिपोर्ट तैयार करें" : "Prepare my report"}<ArrowRight className="size-4" /></button><button className="inline-flex min-h-11 items-center gap-2 rounded-control border border-civic-600 px-5 text-sm font-semibold text-civic-700" onClick={() => openAssistant()}><CircleHelp className="size-4" />{language === "hi" ? "सही विकल्प चुनें" : "Help me choose"}</button></div></div><div className="border-l-0 lg:border-l lg:border-line lg:pl-8"><ResponsiveIllustration assetId="help" language={language} className="mx-auto h-64 w-full max-w-md object-contain" /></div></div></section>

    <section className="border-y border-line bg-canvas"><div className="mx-auto max-w-content px-5 py-10 md:px-8"><div className="grid gap-7 md:grid-cols-[0.7fr_1.3fr]"><div><h2 className="text-[30px] font-semibold tracking-[-0.025em]">{language === "hi" ? "बस तीन बातें" : "Only three things to understand"}</h2><p className="mt-3 text-sm leading-6 text-muted">{language === "hi" ? "पोर्टल की आंतरिक श्रेणियाँ याद रखने की जरूरत नहीं।" : "You should not need to understand portal taxonomy first."}</p></div><ol className="divide-y divide-line border-y border-line">{[
      [language === "hi" ? "बताएं क्या हुआ" : "Tell us what happened", language === "hi" ? "पैसा गया, महिला/बाल से जुड़ी घटना, अन्य साइबर अपराध या अभी निश्चित नहीं।" : "Lost money, Women/Child related, another cybercrime, or not sure yet."],
      [language === "hi" ? "साक्ष्य + समयरेखा व्यवस्थित करें" : "Organise Evidence + Timeline", language === "hi" ? "जो रिकॉर्ड आपके पास हैं उन्हें वास्तविक घटना क्रम से जोड़ें।" : "Connect the records you actually have to the real sequence of events."],
      [language === "hi" ? "आधिकारिक अगले कदम तक जाएँ" : "Continue to the official next step", language === "hi" ? "ThreadZero तैयारी करता है; अंतिम रिपोर्ट या ट्रैकिंग आधिकारिक सेवा पर होती है।" : "ThreadZero prepares; final reporting or case tracking happens on the official service."]
    ].map(([title, body], index) => <li key={title} className="grid gap-3 py-5 sm:grid-cols-[36px_1fr]"><span className="grid size-8 place-items-center rounded-full bg-civic-600 text-sm font-semibold text-white">{index + 1}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{body}</p></div></li>)}</ol></div></div></section>

    <section className="mx-auto max-w-content px-5 py-12 md:px-8 lg:py-16"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-civic-700">{language === "hi" ? "मुख्य तंत्र" : "Core mechanism"}</p><h2 className="mt-3 text-[30px] font-semibold tracking-[-0.025em]">{language === "hi" ? "Evidence ↔ Timeline" : "Evidence ↔ Timeline"}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted">{language === "hi" ? "यह ThreadZero का सबसे उपयोगी हिस्सा है: सिर्फ दस्तावेज़ों की सूची नहीं, बल्कि कौन-सा रिकॉर्ड किस घटना से जुड़ता है।" : "This is the useful part of ThreadZero: not just a list of documents, but which record supports which event."}</p><Link href="/incident" className="mt-5 inline-flex min-h-11 items-center gap-2 font-semibold text-civic-700 underline underline-offset-4">{language === "hi" ? "यह प्रवाह शुरू करें" : "Start this flow"}<ArrowRight className="size-4" /></Link></div><div className="border-y border-line py-5"><div className="grid items-center gap-4 sm:grid-cols-[1fr_auto_1fr]"><div className="py-4"><FileCheck2 className="size-6 text-civic-700" /><h3 className="mt-3 font-semibold">{language === "hi" ? "साक्ष्य" : "Evidence"}</h3><p className="mt-1 text-sm text-muted">{language === "hi" ? "मेरे पास है · नहीं है · पता नहीं" : "Have · Missing · Not sure"}</p></div><ArrowRight className="hidden size-5 text-civic-600 sm:block" /><div className="py-4"><CheckCircle2 className="size-6 text-civic-700" /><h3 className="mt-3 font-semibold">{language === "hi" ? "समयरेखा" : "Timeline"}</h3><p className="mt-1 text-sm text-muted">{language === "hi" ? "कब क्या हुआ और कौन-सा रिकॉर्ड उससे जुड़ता है" : "What happened when, and which record connects to it"}</p></div></div></div></div></section>

    <section className="border-t border-line bg-white"><div className="mx-auto max-w-content px-5 py-10 md:px-8"><h2 className="text-2xl font-semibold">{language === "hi" ? "कुछ और करना है?" : "Need something else?"}</h2><div className="mt-5 divide-y divide-line border-y border-line">{[
      ["/official-tools", <SearchCheck className="size-5" key="check" />, language === "hi" ? "कुछ संदिग्ध जाँचें" : "Check something suspicious", language === "hi" ? "संपर्क/खाता, वेबसाइट/ऐप या मोबाइल/SIM।" : "Contact/account, website/app, or mobile/SIM."],
      ["/learning-corner", <FileCheck2 className="size-5" key="learn" />, language === "hi" ? "साइबर स्कैम समझें" : "Learn about cyber scams", language === "hi" ? "सुरक्षा, पैटर्न, साक्ष्य और आधिकारिक अलर्ट।" : "Safety, patterns, evidence, and official alerts."],
      ["/contact", <CircleHelp className="size-5" key="help" />, language === "hi" ? "सहायता खोजें" : "Find help", language === "hi" ? "1930, सामान्य प्रश्न, आधिकारिक शिकायत और गोपनीयता।" : "1930, FAQs, official escalation, and privacy."]
    ].map(([href, icon, title, body]) => <Link key={String(href)} href={String(href)} className="group grid min-h-20 items-center gap-4 py-4 sm:grid-cols-[44px_1fr_auto]"><span className="grid size-11 place-items-center rounded-full bg-civic-50 text-civic-700">{icon}</span><span><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs leading-5 text-muted">{body}</span></span><ArrowRight className="size-4 text-civic-700 transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
  </>;
}
