export default {
  "meta": {
    "language": "English",
    "languageCode": "en",
    "title": "Financial Cyber Fraud Reporting Guide",
    "qualifier": "Independent concept · Not a government service",
    "disclosure": "Demo information only"
  },
  "nav": {
    "report": "Prepare a report",
    "track": "Track demo",
    "guides": "Guides",
    "resources": "Official tools",
    "about": "About",
    "services": "Services",
    "complaint": "Prepare",
    "trackComplaint": "Track a complaint",
    "suspect": "Report / Check",
    "volunteers": "Cyber Volunteers",
    "learning": "Learning Corner",
    "contact": "Contact",
    "conceptGroup": "This concept",
    "officialGroup": "Official NCRP",
    "prepareDemo": "Prepare a demo record",
    "financialFraud": "Financial fraud complaint",
    "financialFraudNote": "Report financial cyber fraud through NCRP.",
    "womenChildren": "Women or child related cybercrime",
    "womenChildrenAnonymous": "Women or child crime — report anonymously",
    "womenChildrenAnonymousNote": "Choose the anonymous option on the official portal.",
    "womenChildrenTrack": "Women or child crime — register and track",
    "womenChildrenTrackNote": "Use the identifiable official reporting option.",
    "otherCrime": "Other cybercrime",
    "otherCrimeNote": "Open the official category entry.",
    "suspectGroup": "Understand the service",
    "suspectOverview": "Suspect and abuse tools",
    "checkIdentifiers": "Check an identifier",
    "checkIdentifiersNote": "Mobile, email, bank account, social account, or UPI ID.",
    "checkWebsite": "Check a website or app",
    "checkWebsiteNote": "Use the official website and app repository.",
    "reportSuspect": "Report a suspect to I4C",
    "reportSuspectNote": "Opens the official suspect-report form.",
    "reportAbuse": "Report abuse to a social platform",
    "reportAbuseNote": "Find verified intermediary reporting destinations.",
    "tafcop": "Check mobile connections",
    "tafcopNote": "Opens the official TAFCOP service.",
    "gac": "File a GAC appeal",
    "gacNote": "Opens the Grievance Appellate Committee.",
    "learningOverview": "Explore the Learning Corner",
    "reportTrackGroup": "Report and track",
    "helpGroup": "Help and project",
    "language": "Language",
    "primary": "Primary",
    "home": "Home",
    "more": "More",
    "moreTitle": "More services",
    "closeMenu": "Close menu",
    "reportCheck": "Report / Check",
    "evidence": "Evidence",
    "guidesLearning": "Learning",
    "support": "Help",
    "helpSupport": "Help & Support",
    "getStarted": "Get Started"
  },
  "common": {
    "continue": "Continue",
    "back": "Back",
    "edit": "Edit",
    "ready": "Ready",
    "missing": "Missing",
    "optional": "Optional",
    "included": "Include in demo record",
    "notIncluded": "Not included",
    "required": "Required",
    "lastChecked": "Official link last checked 26 August 2026",
    "opensNew": "opens official website in a new tab",
    "officialBoundary": "This link leaves the concept and opens an official service.",
    "actualIncident": "For an actual financial cyber-fraud incident in India",
    "callManually": "Call 1930 manually for urgent help",
    "officialSite": "Use cybercrime.gov.in",
    "noCall": "This concept does not place a call.",
    "noUpload": "No file uploaded. Use fictional demo evidence only.",
    "source": "Source",
    "officialReferences": "Official references",
    "sourceNote": "Information is paraphrased from public NCRP material; use the official destination for current instructions.",
    "learnMore": "Learn more",
    "visitOfficial": "Visit official service",
    "errorsTitle": "There is a problem",
    "demoOnly": "Demo information only",
    "illustrative": "Illustrative preparation state",
    "selected": "Selected",
    "chars": "characters",
    "reset": "Start a fresh demo report",
    "syntheticReference": "Demo reference",
    "nothingSent": "Nothing has been submitted"
  },
  "footer": {
    "title": "Financial Cyber Fraud Reporting Guide",
    "qualifier": "Independent concept · Not a government service",
    "body": "A citizen-first guide for organising cyber-fraud information before using official reporting channels.",
    "helpTitle": "We are here to help you",
    "helpBody": "Prepare the facts, organise your evidence, and find the right next step.",
    "socialUnavailable": "Social profiles are not linked in this independent concept",
    "designed": "Designed for clarity, safety, and confidence.",
    "version": "Version 1.0 · August 2026",
    "services": "Services",
    "learning": "Learning",
    "project": "Project and policies",
    "official": "Official policies and notices",
    "feedback": "Feedback",
    "websitePolicy": "Website policies",
    "privacy": "CyberDost privacy policy",
    "disclaimer": "Disclaimer",
    "notices": "RTI public notice",
    "urgent": "Actual incident? Call 1930 manually and use cybercrime.gov.in.",
    "boundary": "Independent concept · Not a government service.",
    "imageAlt": "Illustration of Indian citizens using a phone and printed guidance together"
  }
};

